replicaCount: 1

image:
  repository: gcr.io/webyn-case-study-staging/webyn-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

environment: staging

env:
  - name: GCP_PROJECT
    value: webyn-case-study-staging
  - name: BUCKET_NAME
    value: webyn-staging-bucket
  - name: LOG_LEVEL
    value: debug 