replicaCount: 1

image:
  repository: gcr.io/webyn-case-study-prod/webyn-app
  tag: stable
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

environment: production

env:
  - name: GCP_PROJECT
    value: webyn-case-study-prod
  - name: BUCKET_NAME
    value: webyn-prod-bucket-20250402
  - name: LOG_LEVEL
    value: info 