apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  chart:
    repository: https://argoproj.github.io/argo-helm
    name: argo-cd
    version: 5.42.2
  values:
    server:
      extraArgs:
        - --insecure
      service:
        type: LoadBalancer
    dex:
      enabled: false
    applicationSet:
      enabled: true 